apiVersion: v1
kind: DeploymentConfig
metadata:
  name: samplejavaci
spec:
  template:
    metadata:  
      labels:
        app: samplejavaci
        deploymentconfig: samplejavaci
      name: samplejavaci
    spec:
      containers:
        - image: sakshikansal/unimoni_poc
          imagePullPolicy: Always
          name: samplejavaci-poc
          volumeMounts:
            - mountPath: /data
              name: volume-0iafj
      volumes:
        - name: volume-0iafj
          persistentVolumeClaim:
            claimName: claim1       
  replicas: 1
  selector:
    app: samplejavaci
    deploymentconfig: samplejavaci   
  triggers:
    - type: ConfigChange
  strategy:
    type: Rolling
  paused: false
  revisionHistoryLimit: 2 
